import { createSlice } from "@reduxjs/toolkit";



const Merchant=createSlice({
    name:"merchant",
    initialState:{
        productGroupData:[],
        productGroupSelected:[], 
        merchantConfigData:[],
        merchantConfigSelected:[],
        storeData:[],
        storeSelected:[],
        terminalUser:[],
        terminalUserSelected:[],
        pumpData:[],
        pumpSelected:[],
        terminalData:[],
        terminalSelected:[],
        transactionData:[],
        transactionSelected:[],
        restrictionGrpData:[],
        restrictionGrpSelected:[],
        restrictionTimeData:[],
        restrictionTimeSelected:[],
        fuelData:[],
        fuelSelected:[],
        terminalProfile:[],
        terminalProfileSelected:[],
        restrictionProdData:[],
        restrictionProdSelected:[],
        restrictionLimitData:[],
        restrictionLimitSelected:[],
        merchantLinkData:[],
        merchantLinkSelected:[],
        merchantRelData:[],
        merchantRelSelected:[],
        merchantTranData:[],
        merchantTranSelected:[],

    },
    reducers:{
        setProductGroupData:(state,action)=>{
            state.productGroupData=action.payload;
        },
        setProductGroupSelected:(state,action)=>{
            state.productGroupSelected=action.payload
        },
      
        setMerchantConfigData:(state,action)=>{
            state.merchantConfigData=action.payload
        },
        setMerchantConfigSelected:(state,action)=>{
            state.merchantConfigSelected=action.payload
        },
        setStoreData:(state,action)=>{
            state.storeData=action.payload
        },
        setStoreSelected:(state,action)=>{
            state.storeSelected=action.payload
        },
        setTerminalUser:(state,action)=>{
            state.terminalUser=action.payload
        },
        setTerminalUserSelected:(state,action)=>{
            state.terminalUserSelected=action.payload
        },
        setPumpData:(state,action)=>{
            state.pumpData=action.payload
        },
        setPumpSelected:(state,action)=>{
            state.pumpSelected=action.payload
        },
        setTerminal:(state,action)=>{
            state.terminalData=action.payload
        },
        setTerminalSelected:(state,action)=>{
            state.terminalSelected=action.payload
        },
        setTransaction:(state,action)=>{
            state.transactionData=action.payload
        },
        setTransactionSelected:(state,action)=>{
            state.transactionSelected=action.payload
        },
        setRestrictionGrp:(state,action)=>{
            state.restrictionGrpData=action.payload
        },
        setRestrictionGrpSelected:(state,action)=>{
            state.restrictionGrpSelected=action.payload
        },
        setrestrictionTime:(state,action)=>{
            state.restrictionTimeData=action.payload

        },
        setRestrictionTimeSelected:(state,action)=>{
            state.restrictionTimeSelected=action.payload
        },
        setFuelData:(state,action)=>{
            state.fuelData=action.payload
        },
        setFuelSelected:(state,action)=>{
            state.fuelSelected=action.payload
        },
        setTerminalProfile:(state,action)=>{
            state.terminalProfile=action.payload
        },
        setTerminalProfileSelected:(state,action)=>{
            state.terminalProfileSelected=action.payload
        },
        setRestrictionProd:(state,action)=>{
            state.restrictionProdData=action.payload
        },
        setRestrictionProdSelected:(state,action)=>{
            state.restrictionProdSelected=action.payload
        },
        setRestrictionLimit:(state,action)=>{
            state.restrictionLimitData=action.payload
        },
        setRestrictionLimitSelected:(state,action)=>{
            state.restrictionLimitSelected=action.payload
        },
        setMerchantLinkData:(state,action)=>{
            state.merchantLinkData=action.payload
        },
        setMerchantLinkSelected:(state,action)=>{
            state.merchantLinkSelected=action.payload
        },
        setMerchantRelData:(state,action)=>{
            state.merchantRelData=action.payload
        },
        setMerchantRelSelected:(state,action)=>{
            state.merchantRelSelected=action.payload
        },
        setMerchantTranData:(state,action)=>{
            state.merchantTranData=action.payload
        },
        setMerchantTranSelected:(state,action)=>{
            state.merchantTranSelected=action.payload
        },

        clearUserDataMerchant:(state)=>{
            state.productGroupData=[];
            state.productGroupSelected=[];  
            state.merchantConfigData=[];
            state.merchantConfigSelected=[];
            state.storeData=[];
            state.storeSelected=[];
            state.terminalUser=[];
            state.terminalUserSelected=[];
            state.pumpData=[];
            state.pumpSelected=[];
            state.terminalData=[];
            state.terminalSelected=[];
            state.transactionData=[];
            state.transactionSelected=[];
            state.restrictionGrpData=[];
            state.restrictionGrpSelected=[];
            state.restrictionTimeData=[];
            state.restrictionTimeSelected=[];
            state.fuelData=[];
            state.fuelSelected=[];
            state.terminalProfile=[];
            state.terminalProfileSelected=[];
            state.restrictionProdData=[];
            state.restrictionProdSelected=[];
            state.restrictionLimitData=[];
            state.restrictionLimitSelected=[];
            state.merchantLinkData=[];
            state.merchantLinkSelected=[];
            state.merchantRelData=[];
            state.merchantRelSelected=[];
            state.merchantTranData=[];
            state.merchantTranSelected=[];
        }

    }
})


export const {
    setProductGroupData,
    setProductGroupSelected,
    setMerchantConfigData,
    setMerchantConfigSelected,
    setStoreData,
    setStoreSelected,
    setTerminalUser,
    setTerminalUserSelected,
    setPumpData,
    setPumpSelected,
    setTerminal,
    setTerminalSelected,
    setTransactionSelected,
    setTransaction,
    setRestrictionGrp,
    setRestrictionGrpSelected,
    setRestrictionTimeSelected,
    setrestrictionTime,
    setFuelData,
    setFuelSelected,
    setTerminalProfile,
    setTerminalProfileSelected,
    setRestrictionProd,
    setRestrictionProdSelected,
    setRestrictionLimit,
    setRestrictionLimitSelected,
    setMerchantLinkData,
    setMerchantLinkSelected,
    setMerchantRelData,
    setMerchantRelSelected,
    setMerchantTranData,
    setMerchantTranSelected
    
}=Merchant.actions


export default Merchant.reducer