export const ROUTES = {
  LOGIN: '/',
  HOME: '/customer/home',
  SEND_START: '/customer/send',
  SEND_CONFIRM: '/customer/send/confirm',
  SEND_SUCCESS: '/customer/send/success',
  SEND_DETAILS: '/customer/send/details',
  RECEIVE: '/customer/receive',
  WALLET_TO_CARD: '/customer/wallet-to-card',
  WALLET_TO_CARD_CONFIRM: '/customer/wallet-to-card/confirm',
  WALLET_TO_CARD_SUCCESS: '/customer/wallet-to-card/success',
  WALLET_TO_CARD_DETAILS: '/customer/wallet-to-card/details',
  CARD_TO_CARD: '/customer/card-to-card',
  CARD_TO_CARD_CONFIRM: '/customer/card-to-card/confirm',
  CARD_TO_CARD_SUCCESS: '/customer/card-to-card/success',
  CARD_TO_CARD_DETAILS: '/customer/card-to-card/details',
  CASH_IN: '/customer/cash-in',
  CASH_IN_CONFIRM: '/customer/cash-in/confirm',
  CASH_IN_SUCCESS: '/customer/cash-in/success',
  CASH_IN_DETAILS: '/customer/cash-in/details',
  HISTORY: '/customer/history',
  TRANSACTION_DETAILS: '/customer/history/:id',
  CARDS: '/customer/cards',
  CARD_DETAILS: '/customer/cards/:id',
  PROFILE: '/customer/profile',
  PROFILE_DETAILS: '/customer/profile/details',
}


