export const ROUTES = {
  LOGIN: '/login',
  PASSCODE: '/passcode',
  HOME: '/home',
  SEND_START: '/send',
  SEND_CONFIRM: '/send/confirm',
  SEND_SUCCESS: '/send/success',
  RECEIVE: '/receive',
  SCAN: '/scan',
  SCAN_CONFIRM: '/scan/confirm',
  CASH_IN: '/cash-in',
  CASH_IN_CONFIRM: '/cash-in/confirm',
  CASH_IN_SUCCESS: '/cash-in/success',
  CASH_OUT: '/cash-out',
  CASH_OUT_CONFIRM: '/cash-out/confirm',
  CASH_OUT_SUCCESS: '/cash-out/success',
  HISTORY: '/history',
  TRANSACTION_DETAILS: '/history/:id',
  CARDS: '/cards',
  CARD_DETAILS: '/cards/:id',
  PROFILE: '/profile',
  PROFILE_DETAILS: '/profile/details',
  CHANGE_PASSCODE: '/profile/change-passcode',
}

